# Generated by Django 5.2.13 on 2026-04-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
