SITE = {
    "name": "Sris Snehidi Fashion Institute",
    "tagline": "Sharpen Your Creativity To Shape Your Own Identity",
    "about": [
        "At Sri's Snehidi Fashion Institute, we bring over 11+ years of expertise training in the field of fashion. We are a registered institute under MSME and hold a trademark, offering certified courses in Fashion Designing and Aari Embroidery.",
        "Our programs are thoughtfully designed exclusively for women with a passion to learn and grow in fashion, with a simple and structured syllabus. We ensure quality learning at an affordable fee, making it accessible for every aspiring learner to build skills with confidence and create their own identity.",
        "Fashion is a field with a never-ending market, where with dedication and quality work, one can grow and excel. Our training focuses on practical exposure and continuous guidance to help learners step into real opportunities.",
        "Over the years, we have built a strong community of learners, many of whom have successfully transformed their skills into independent ventures. We take pride in creating a warm and supportive environment where every woman feels confident to grow and succeed.",
    ],
    "phone": "+91 9092518668",
    "whatsapp": "919092518668",
    "address": "2rd Floor, Door no.33, Plot no.5/7, Sarathy Nagar 3rd Street, Puzhuthivakkam, Chennai-600091",
    "instagram": "https://instagram.com/srissnehidi",
    "facebook": "https://www.facebook.com/people/Sris-Snehidi-Fashion-Institute/100063580346645/#",
    "youtube": "https://www.youtube.com/@srissnehidifashioninstitut9049",
}

TRAINER = {
    "name": "Sridevi Saravanan",
    "title": "Founder & Master Trainer, Sri's Snehidi Fashion Institute",
    "bio": [
        "Sridevi Saravanan, Founder of Sri's Snehidi Fashion Institute, is a passionate homemaker-turned-entrepreneur with over 25 years of experience in fashion and 11+ years of expertise in training.",
        "She holds an academic background in accounts and has completed various professional courses in fashion, building strong practical expertise in the field. She has also completed M.Sc. in Yoga, which helps her understand the strengths of different women and guide each student with a personalized approach.",
        "She has successfully trained 300+ women, many of whom have gone on to build their own identity and income in the fashion industry. Known for her patient and encouraging teaching style, she ensures every student learns with clarity and confidence, regardless of their background.",
        "She is also a proud world record holder in Kalam's Book of Records for the \"Fastest Speller of Antonym Words in Backwords,\" which she achieved in her 40s. With this, she proves that age is not a barrier to learning or to excel.",
        "With a strong vision to empower women through skill-based learning, she focuses on practical training, perfection in finishing, and real-world application. She strongly believes that a friendly and supportive learning environment helps every woman unlock her potential and excel with confidence.",
    ],
    "photo": "https://res.cloudinary.com/dmvdowhru/image/upload/v1777301921/IMG-20240719-WA0045_1_gq3jyc.jpg"
}

COURSES = {
    "regular": [
        {
            "name": "Certified Course: Basic Fashion Designing",
            "badge": "",
            "description": "Build a strong foundation in fashion with our beginner-friendly course designed especially for women who are passionate about learning. This program covers essential skills like measurements, basic garment construction, and understanding fabrics in a simple and practical way.",
            "highlights": [
                "Starter kit provided",
                "Includes hands-on practice with motored sewing machines",
                "Fitting correction techniques",
                "One-to-one mentoring support",
                "Detailed practical guidance",
                "Lifetime community access",
            ],
            "duration": "3 Months",
            "schedule": "3 Days a week (Mon, Wed & Fri)",
            "timings": "10:30am to 1:00pm",
            "fee": "Rs 20,000/-",
            "note": "For a detailed explanation of the syllabus and the free add-on sessions included in the course, we warmly invite you to visit our institute.",
            "cta": "Book an Appointment Now",
            "phone": "9092518668",
            "syllabus": [],
        },
        {
            "name": "Certified Course: Fashion Designing",
            "badge": "Our Signature Course",
            "description": "This comprehensive course begins with the fundamentals covered in our Basic Fashion Designing program and gradually takes your creativity to the next level with professional-level training. From designing to execution, this course equips you with complete knowledge to create your own garments and even start a fashion business.",
            "highlights": [
                "Starter kit provided",
                "Includes hands-on practice with motored sewing machines",
                "Advanced garment construction",
                "One-to-one mentoring support",
                "Detailed practical guidance",
                "Lifetime community access",
            ],
            "duration": "5 Months",
            "schedule": "3 Days a week (Mon, Wed & Fri)",
            "timings": "10:30am to 1:00pm",
            "fee": "Rs 35,000/-",
            "note": "For a detailed explanation of the syllabus and the free add-on sessions included in the course, we warmly invite you to visit our institute.",
            "cta": "Book an Appointment Now",
            "phone": "9092518668",
            "syllabus": [],
        },
        {
            "name": "Certified Course: Aari Embroidery (Online)",
            "badge": "Most Enrolled Course",
            "description": "Experience the art of Aari Embroidery at your own pace through our thoughtfully designed online program, combining live interactive sessions with high-quality pre-recorded lessons for flexible learning. Personalized support, including doubt clarification and assignment submissions, is seamlessly managed through WhatsApp.",
            "highlights": [
                "All-inclusive Aari material kit shipped to your doorstep (with rectangular stand)",
                "Certificate dispatched after successful course completion",
                "One-to-one mentoring support",
                "Lifetime access to Sris Snehidi community",
            ],
            "duration": "2 to 6 months (depends on your learning)",
            "schedule": "As per your convenience",
            "timings": "Flexible",
            "fee": "Rs 8,000/- (Including the Aari kit)",
            "note": "",
            "cta": "Call & Register Now",
            "phone": "9092518668",
            "syllabus": [
                "Introduction to Embroidery",
                "100+ stitches",
                "Explanation of names and uses of Aari materials",
                "Creating Aari designs",
                "Tracing techniques",
                "Stencil techniques",
                "Neck and sleeve marking on blouse material",
                "Pricing and material knowledge",
                "Practical skill guidance",
                "Fashion business and marketing",
            ],
        },
        {
            "name": "Certified Course: Aari Embroidery (Offline)",
            "badge": "",
            "description": "Aari embroidery is a valuable skill that blends creativity with income opportunities. With our step-by-step guidance, you can learn and master it with confidence. To suit your convenience, we offer Aari Embroidery courses in three different formats.",
            "highlights": [
                "Aari material kit needed for the class",
                "Neckline and sleeve marking on fabric",
                "Concept of Stencil",
                "Concept of varieties of tracing",
                "Creating designs",
                "Knowledge on price fixing for Aari work",
                "Lifetime access to Sris Snehidi Community",
            ],
            "tiers": [
                {
                    "name": "Basic Aari Embroidery",
                    "detail": "2 Months Course (16 classes approx) — 75 stitches",
                    "fee": "Rs 8,000/- (Including materials)",
                },
                {
                    "name": "Aari Embroidery",
                    "detail": "4 Months Course (32 classes approx) — 125+ stitches",
                    "fee": "Rs 14,000/- (Including materials)",
                },
                {
                    "name": "3D Aari Work",
                    "detail": "5 classes (only for students who completed full Aari course)",
                    "fee": "Rs 3,000/- (Including materials)",
                },
            ],
            "duration": "2 to 5 months depending on chosen tier",
            "schedule": "Two days a week (Tue & Thu)",
            "timings": "10:30am to 1:00pm",
            "free_offer": "3D course is FREE for students who opt for the Full Aari Embroidery course",
            "note": "For a detailed explanation of the syllabus and the free add-on sessions included in the course, we request you to visit our institute in person.",
            "cta": "Book an Appointment Now",
            "phone": "9092518668",
            "syllabus": [],
        },
    ],
    "upcoming": [
        {
            "name": "Basic Fashion Designing",
            "batch": "June 2026 Batch",
            "offers": ["Early Bird Offer", "Akshayatritiya Offer"],
        },
        {
            "name": "Fashion Designing",
            "batch": "June 2026 Batch",
            "offers": ["Early Bird Offer", "Akshayatritiya Offer"],
        },
        {
            "name": "Aari Embroidery (Online)",
            "batch": "",
            "offers": ["Akshayatritiya Offer"],
        },
    ],
    "workshop": [
        {
            "name": "Saree Pre-pleating",
            "description": "A detailed hands-on practice session",
        },
        {
            "name": "Fabric Painting",
            "description": "An exclusive 4-day workshop for kids",
        },
        {
            "name": "Decode Success — Your Way",
            "description": "A free session for teens in your area",
            "free": True,
        },
    ],
}
